name: Generate Base Main Coverage Report

on:
  push:
    branches: [main]
jobs:
  base-coverage:
    runs-on: ubuntu-latest   
    steps:
        - name: 'Checkout Github Action'
          uses: actions/checkout@master

        - name: Cache turbo build setup
          uses: actions/cache@v4
          with:
            path: .turbo
            key: ${{ runner.os }}-turbo-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-turbo-

        - name: Set up Node.js 
          uses: actions/setup-node@v1
          with:
            node-version: 20.x  

        - uses: pnpm/action-setup@v3
          with:
            version: 8
            run_install: |
              - recursive: true
                args: [--frozen-lockfile, --strict-peer-dependencies]   

        - run: pnpm turbo run test:lib --cache-dir=.turbo 
        - run: npx cobertura-merge-globby -o coverage.xml --files="**/cobertura-coverage.xml"
        - uses: clearlyip/code-coverage-report-action@v4
          with:
            #Location of the generated coverage file
            filename: 'coverage.xml'