name: Test Runner

on:
  repository_dispatch:
    types: [vsix]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        with:
          token: ${{ secrets.AUTOMATION_PAT }}

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm ci

      - name: 'Version Bump'
        run: git config --global user.email $GITHUB_ACTOR && git config --global user.name release-automation-${GITHUB_ACTOR}@microsoft.com && npm run bump && npm install

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.AUTOMATION_PAT }}
          branch: ${{ github.ref }}

  build:
    runs-on: ubuntu-latest
    needs: bump-version
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # checkout the repo
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - name: Set up Node.js version 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm ci
      - run: npx nx build vs-code-data-mapper
      - run: npm run vscode:data-mapper:pack

      - name: Archive VSIX
        uses: actions/upload-artifact@v3
        with:
          #name: data_mapper.vsix
          path: |
            dist/apps/vs-code-data-mapper/*.vsix
